module sdram_top_axi(
  input         clock,
  input         reset,
  output        in_aw_ready,
  input         in_aw_valid,
  input  [31:0] in_aw_bits_addr,
  input  [3:0]  in_aw_bits_id,
  input  [7:0]  in_aw_bits_len,
  input  [2:0]  in_aw_bits_size,
  input  [1:0]  in_aw_bits_burst,
  input         in_aw_bits_lock,
  input  [3:0]  in_aw_bits_cache,
  input  [2:0]  in_aw_bits_prot,
  input  [3:0]  in_aw_bits_qos,
  output        in_w_ready,
  input         in_w_valid,
  input  [31:0] in_w_bits_data,
  input  [3:0]  in_w_bits_strb,
  input         in_w_bits_last,
  input         in_b_ready,
  output        in_b_valid,
  output [1:0]  in_b_bits_resp,
  output [3:0]  in_b_bits_id,
  output        in_ar_ready,
  input         in_ar_valid,
  input  [31:0] in_ar_bits_addr,
  input  [3:0]  in_ar_bits_id,
  input  [7:0]  in_ar_bits_len,
  input  [2:0]  in_ar_bits_size,
  input  [1:0]  in_ar_bits_burst,
  input         in_ar_bits_lock,
  input  [3:0]  in_ar_bits_cache,
  input  [2:0]  in_ar_bits_prot,
  input  [3:0]  in_ar_bits_qos,
  input         in_r_ready,
  output        in_r_valid,
  output [1:0]  in_r_bits_resp,
  output [31:0] in_r_bits_data,
  output        in_r_bits_last,
  output [3:0]  in_r_bits_id,

  output        sdram_clk,
  output        sdram_cke,
  output        sdram_cs,
  output        sdram_ras,
  output        sdram_cas,
  output        sdram_we,
  output [12:0] sdram_a,
  output [ 1:0] sdram_ba,
  output [ 1:0] sdram_dqm,
  inout  [15:0] sdram_dq
);

  wire sdram_dout_en;
  wire [15:0] sdram_dout;
  assign sdram_dq = sdram_dout_en ? sdram_dout : 16'bz;
  sdram_axi #(
    .SDRAM_MHZ(100),
    .SDRAM_ADDR_W(24),
    .SDRAM_COL_W(9),
    .SDRAM_READ_LATENCY(2)
  ) u_sdram_axi(
    .clk_i(clock),
    .rst_i(reset),
    .inport_awvalid_i(in_aw_valid),
    .inport_awaddr_i(in_aw_bits_addr),
    .inport_awid_i(in_aw_bits_id),
    .inport_awlen_i(in_aw_bits_len),
    .inport_awburst_i(in_aw_bits_burst),
    .inport_wvalid_i(in_w_valid),
    .inport_wdata_i(in_w_bits_data),
    .inport_wstrb_i(in_w_bits_strb),
    .inport_wlast_i(in_w_bits_last),
    .inport_bready_i(in_b_ready),
    .inport_arvalid_i(in_ar_valid),
    .inport_araddr_i(in_ar_bits_addr),
    .inport_arid_i(in_ar_bits_id),
    .inport_arlen_i(in_ar_bits_len),
    .inport_arburst_i(in_ar_bits_burst),
    .inport_rready_i(in_r_ready),

    .inport_awready_o(in_aw_ready),
    .inport_wready_o(in_w_ready),
    .inport_bvalid_o(in_b_valid),
    .inport_bresp_o(in_b_bits_resp),
    .inport_bid_o(in_b_bits_id),
    .inport_arready_o(in_ar_ready),
    .inport_rvalid_o(in_r_valid),
    .inport_rdata_o(in_r_bits_data),
    .inport_rresp_o(in_r_bits_resp),
    .inport_rid_o(in_r_bits_id),
    .inport_rlast_o(in_r_bits_last),
    .sdram_clk_o(sdram_clk),
    .sdram_cke_o(sdram_cke),
    .sdram_cs_o(sdram_cs),
    .sdram_ras_o(sdram_ras),
    .sdram_cas_o(sdram_cas),
    .sdram_we_o(sdram_we),
    .sdram_dqm_o(sdram_dqm),
    .sdram_addr_o(sdram_a),
    .sdram_ba_o(sdram_ba),
    .sdram_data_input_i(sdram_dq),
    .sdram_data_output_o(sdram_dout),
    .sdram_data_out_en_o(sdram_dout_en)
  );

  wire unused_axi_attributes = &{1'b0, in_aw_bits_size,
    in_aw_bits_lock, in_aw_bits_cache, in_aw_bits_prot, in_aw_bits_qos,
    in_ar_bits_size, in_ar_bits_lock, in_ar_bits_cache, in_ar_bits_prot,
    in_ar_bits_qos};

endmodule
